language: php

dist: trusty

services:
  - mysql

sudo: false

php:
  - 7.0.8
  - 7.1

matrix:
  fast_finish: true

  include:
    - php: 7.0.8
      env: PHPCS=1

before_script:
  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:~2.1; fi
  - if [[ $PHPCS != 1 ]]; then composer install; fi
  - if [[ $PHPCS != 1 ]]; then composer require phpunit/phpunit:"^5.7|^6.0"; fi
  - if [[ $PHPCS != 1 ]]; then composer run-script post-install-cmd --no-interaction; fi
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wawh_testing'

script:
  - if [[ $PHPCS != 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot; fi

notifications:
  email: false
  slack: cber:ZeUxtjnpHNEYCkMtUBhskwXl

addons:
  code_climate:
    repo_token: 1027980f0aa898e1e6b371f40edc73852473be14fc45255cbda8beaf2db16e37

after_success:
  - vendor/bin/test-reporter
